apiVersion: v1
kind: Pod
metadata:
  name: container-pod
spec:
  containers:
  - name: container
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /data
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 10
  volumes:
  - name: data-volume
    emptyDir: {}