apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    version: v1.0.0
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80